name: Build docs

on:
  push:
    branches: ["netlify"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  PRODUCT: help-module/hp
  ARTIFACT: webHelpHP2-all.zip
  NETLIFY_AUTH_TOKEN: mcXhSMLocW7BLvEGGdWRbgJQZ3Bt9d3pfnWmZpT6fL0
  NETLIFY_SITE_ID: e97f80dc-ba67-4659-b800-613732c4ca75

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v1
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webhelp
          path: artifacts/${{ env.ARTIFACT }}
          retention-days: 7


  netlify:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: webhelp
      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.ARTIFACT }} -d ./_build
      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: true